### ISSUE TITLE
Warning: Undefined array key "mandatory"

### ISSUE THREAD

**Issue by christianbarkowsky** [contao-community-alliance/contao-multicolumnwizard-bundle#118] opened 2022-02-23 10:51 UTC
Contao 4.13
PHP 8

When creating a new content element with an multiColumnWizard inputType.

For example: fritzmg/contao-swiper 

<img width="1122" alt="Bildschirmfoto 2022-02-23 um 11 51 55" src="https://user-images.githubusercontent.com/1230547/155305387-637dab88-c833-4aa5-a999-ae6339c5921e.png">

**Comment by fritzmg** [comment] 2022-02-23 11:47
Duplicate of https://github.com/contao-community-alliance/contao-multicolumnwizard-bundle/pull/116

**Comment by zonky2** [comment] 2022-02-23 12:05
see #116

**Closed as completed by zonky2** 2022-02-23 12:05 UTC
Labels: bug, duplicate
